import type { LucideIcon } from "lucide-react";
import {
  Accessibility,
  Activity,
  AirVent,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Apple,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Backpack,
  BadgeDollarSign,
  Banana,
  Banknote,
  Barcode,
  Bath,
  Battery,
  Bed,
  Beer,
  Bell,
  Bike,
  Bluetooth,
  Book,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Carrot,
  Check,
  CheckCircle,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  Citrus,
  Clapperboard,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CookingPot,
  Copy,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Database,
  DollarSign,
  Download,
  Drama,
  Droplet,
  Dumbbell,
  Edit,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  Fan,
  FileText,
  Film,
  Filter,
  Flag,
  Flame,
  Flower,
  Folder,
  Footprints,
  Fuel,
  Gauge,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Grape,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Highlighter,
  History,
  Home,
  IceCream,
  Info,
  JapaneseYen,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Link,
  Lock,
  Mail,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  Mic,
  Milk,
  Minus,
  MinusCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Music,
  Navigation,
  Package,
  Paintbrush,
  Palmtree,
  Pen,
  PenLine,
  Pencil,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug,
  Plus,
  PlusCircle,
  Popcorn,
  PoundSterling,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Scissors,
  Search,
  Server,
  Settings,
  Share,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Target,
  Thermometer,
  Ticket,
  Timer,
  ToyBrick,
  Train,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Unlock,
  Upload,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Wallet,
  WalletMinimal,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  // Popular icons (keys must match IconPicker.tsx POPULAR_ICONS)
  tag: Tag,
  wallet: Wallet,
  utensils: Utensils,
  car: Car,
  home: Home,
  "shopping-bag": ShoppingBag,
  film: Film,
  plane: Plane,
  heart: Heart,
  gift: Gift,
  graduation: GraduationCap,
  dumbbell: Dumbbell,
  coffee: Coffee,
  smartphone: Smartphone,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  stethoscope: Stethoscope,
  piggybank: PiggyBank,
  "credit-card": CreditCard,
  receipt: Receipt,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  landmark: Landmark,
  coins: Coins,
  dollar: DollarSign,
  plus: Plus,
  minus: Minus,
  transfer: ArrowLeftRight,
  // Standard lucide names for the same popular icons
  "graduation-cap": GraduationCap,
  "piggy-bank": PiggyBank,
  "dollar-sign": DollarSign,
  "arrow-left-right": ArrowLeftRight,
  // Finance
  banknote: Banknote,
  euro: Euro,
  "pound-sterling": PoundSterling,
  "japanese-yen": JapaneseYen,
  "trending-down": TrendingDown,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  building: Building,
  "building-2": Building2,
  store: Store,
  "badge-dollar-sign": BadgeDollarSign,
  "circle-dollar-sign": CircleDollarSign,
  "wallet-minimal": WalletMinimal,
  "hand-coins": HandCoins,
  // Food & drink
  "utensils-crossed": UtensilsCrossed,
  pizza: Pizza,
  sandwich: Sandwich,
  soup: Soup,
  salad: Salad,
  "ice-cream": IceCream,
  cookie: Cookie,
  cake: Cake,
  croissant: Croissant,
  beer: Beer,
  wine: Wine,
  "cup-soda": CupSoda,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  citrus: Citrus,
  carrot: Carrot,
  milk: Milk,
  "cooking-pot": CookingPot,
  "chef-hat": ChefHat,
  // Transport
  bus: Bus,
  train: Train,
  truck: Truck,
  bike: Bike,
  fuel: Fuel,
  gauge: Gauge,
  ship: Ship,
  sailboat: Sailboat,
  anchor: Anchor,
  navigation: Navigation,
  "map-pin": MapPin,
  compass: Compass,
  // Home
  sofa: Sofa,
  bed: Bed,
  bath: Bath,
  lamp: Lamp,
  fan: Fan,
  "air-vent": AirVent,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  brush: Brush,
  "spray-can": SprayCan,
  sparkles: Sparkles,
  // Health
  pill: Pill,
  thermometer: Thermometer,
  activity: Activity,
  "heart-pulse": HeartPulse,
  accessibility: Accessibility,
  "person-standing": PersonStanding,
  // Tech
  laptop: Laptop,
  monitor: Monitor,
  tv: Tv,
  headphones: Headphones,
  camera: Camera,
  video: Video,
  mic: Mic,
  speaker: Speaker,
  bluetooth: Bluetooth,
  battery: Battery,
  plug: Plug,
  cpu: Cpu,
  database: Database,
  server: Server,
  printer: Printer,
  // Shopping
  "shopping-cart": ShoppingCart,
  package: Package,
  box: Box,
  shirt: Shirt,
  footprints: Footprints,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  crown: Crown,
  // Entertainment
  music: Music,
  radio: Radio,
  popcorn: Popcorn,
  ticket: Ticket,
  clapperboard: Clapperboard,
  drama: Drama,
  puzzle: Puzzle,
  "toy-brick": ToyBrick,
  book: Book,
  "book-open": BookOpen,
  // Nature
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-lightning": CloudLightning,
  wind: Wind,
  waves: Waves,
  mountain: Mountain,
  "tree-pine": TreePine,
  "tree-deciduous": TreeDeciduous,
  "palm-tree": Palmtree,
  flower: Flower,
  leaf: Leaf,
  sprout: Sprout,
  flame: Flame,
  snowflake: Snowflake,
  // UI / common
  check: Check,
  x: X,
  search: Search,
  menu: Menu,
  filter: Filter,
  bell: Bell,
  settings: Settings,
  user: User,
  users: Users,
  star: Star,
  flag: Flag,
  pin: Pin,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  history: History,
  "rotate-ccw": RotateCcw,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  download: Download,
  upload: Upload,
  share: Share,
  link: Link,
  "external-link": ExternalLink,
  "file-text": FileText,
  folder: Folder,
  archive: Archive,
  mail: Mail,
  phone: Phone,
  "message-circle": MessageCircle,
  info: Info,
  "help-circle": HelpCircle,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "plus-circle": PlusCircle,
  "minus-circle": MinusCircle,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "more-vertical": MoreVertical,
  "more-horizontal": MoreHorizontal,
  trash: Trash,
  "trash-2": Trash2,
  pencil: Pencil,
  edit: Edit,
  copy: Copy,
  scissors: Scissors,
  eye: Eye,
  "eye-off": EyeOff,
  "qr-code": QrCode,
  barcode: Barcode,
  // Education / work
  school: School,
  backpack: Backpack,
  pen: Pen,
  "pen-line": PenLine,
  highlighter: Highlighter,
  ruler: Ruler,
  calculator: Calculator,
  // Sports / achievements
  trophy: Trophy,
  medal: Medal,
  award: Award,
  target: Target,
};

export function getIconByName(name: string | null | undefined): LucideIcon {
  if (!name) return Tag;
  return ICONS[name.toLowerCase()] ?? Tag;
}
